### ISSUE TITLE
Clean puppeteer_dev_chrome_profile

### ISSUE THREAD

**Issue by Beluk** [jean-humann/docs-to-pdf#132]
Puppeteer saves a lot of GB's in tmp folder and never clears it. I ran out of disc space. Would be nice if this is cleaned up.
https://github.com/puppeteer/puppeteer/issues/1791#issuecomment-1311558279

**Comment by jean-humann** [comment]
@Beluk fixed in [v0.3.1](https://github.com/jean-humann/docs-to-pdf/releases/tag/v0.3.1)
Let me know if it's fine on your side
