### ISSUE TITLE
Error: Could not find Google Chrome executable for channel 'stable' at '/opt/google/chrome/chrome'.

### ISSUE THREAD

**Issue by Beluk** [jean-humann/docs-to-pdf#145]
Since v0.3.1 this error shows up on start, with v0.3.0 everything works fine

**Comment by jean-humann** [comment]
Hi @Beluk , what browser are you using Chromium ? Seem related to this [puppeteer PR](https://github.com/puppeteer/puppeteer/pull/10536). Unforunatly, I have to keep this version because it resolves a critical CVE on puppeteer side. I will try to find an other way to do it

**Comment by Beluk** [comment]
Hi @jean-humann not sure about your question. In Windows i use Chromium but i get the same error. The build machine which running on debian there is no chromium installed. With v0.3.0 it was not necessary. On both machine the same error occurs. So with v0.3.1 i'm no able to use it anymore. Do you know if i must install or setup anything different?

**Comment by jean-humann** [comment]
Thanks for those details, I clearly see the issue now. I remove the dependency to puppeteer to only use puppeteer-core. The downsize of that, is that puppeteer-core doesn't install a builtin chromium. I will add this feature this week.

**Comment by jean-humann** [comment]
@Beluk sorry for the delay, could you try again with release 0.5.1 please ?

**Comment by Beluk** [comment]
> @Beluk sorry for the delay, could you try again with release 0.5.1 please ? 

I will do next week, when back from vacation.

**Comment by Beluk** [comment]
Still gettting the same error on linux and on windows machine. :-(

**Comment by jean-humann** [comment]
@Beluk the fix #210 is available in V0.6.1.
Could you try and validate if it works for you, please ? 
Thanks !

**Comment by Beluk** [comment]
LGTM! Thx for the fix!
