### ISSUE TITLE
An option to control whether all of `<details>` elements are opened

### ISSUE THREAD

**Issue by tats-u** [jean-humann/docs-to-pdf#196]
https://docusaurus.io/docs/markdown-features#details

`<details>` allows us to hide contents only for experts. It would be nice if we can control whether `<details>` are opened.

In the current version, all of `<details>` are closed.

For beginners  
![image](https://github.com/jean-humann/docs-to-pdf/assets/12870451/2927ed82-e225-4004-8ea0-d151f11405de)

For experts  
![image](https://github.com/jean-humann/docs-to-pdf/assets/12870451/01f620d0-f17e-4ccf-872c-0e31e6188a91)

Can Puppeteer do this operation before printing the jointed page?

```mermaid
flowchart TD

S(Start) --> F[Find and open closed elements]
F --> C{New closed\nelements appeared?}
C -->|Yes| F
C -->|No| Done(Done)
```

**Comment by jean-humann** [comment]
Hi @tats-u , thanks for the feedback 👍 
By default, the `details`should be open cf :   https://github.com/jean-humann/docs-to-pdf/blob/master/src/utils.ts#L238
I will have a look this week on this bug.

**Comment by tats-u** [comment]
When I used it before, everything was closed, but I don't know if it was after the fix was in.
I tried to test again but obstructed by #198.

**Comment by codingluke** [comment]
I can confirm, that also in my tests `<details>` where closed.

**Comment by jean-humann** [comment]
This PR #203 should fix this issue, just need to fix unit test and let's merge !
